import type { ApiLocale } from '../../lib/api/client';
export const schoolCopy = {
  zh: {
    title: '我的选校方案', subtitle: '先了解项目，再决定是否加入申请。',
    emptyTitle: '还没有选校方案', emptyBody: '当前账号没有可选择的项目。本版本只查看已有方案，完善档案不会自动生成选校结果。已有的网页端测试方案会在这里同步显示。',
    freeBoundary: '本版本可查看已有方案，不会自动生成或重新搜索院校。',
    running: '选校任务仍在进行中。这里会保留已有方案，你可以稍后刷新查看最新结果。',
    failed: '最近一次选校任务未完成。已有方案仍可查看，但不会在这里自动重试生成。',
    cancelled: '最近一次选校任务已取消。已有方案仍可查看。',
    stale: '你的留学档案已更新。现有方案尚未重新评估，请对照最新背景谨慎选择。',
    profile: '完善留学档案', reload: '刷新方案', back: '返回我的申请', view: '查看项目',
    details: '项目详情', add: '加入我的申请', adding: '正在加入…', added: '已加入我的申请', viewApplication: '查看申请',
    notSubmitted: '加入后会建立申请档案，不代表已向学校提交申请。',
    unavailable: '这个项目当前不能加入申请，请返回方案查看最新结果。',
    missingSelection: '这个项目已不在当前方案中。请返回选校方案重新选择。',
    backPlan: '返回选校方案', uncertain: '尚未收到添加结果，申请可能已经建立。请先核对结果，再决定下一步。',
    check: '核对添加结果', checking: '正在核对…', retryReady: '暂未查到这项申请。你可以再次加入，同一项目只会保留一份申请档案。',
    denied: '暂时无法加入这个项目，请刷新方案确认它仍可选择。',
    leaveTitle: '添加结果尚未确认', leaveBody: '离开不会撤销已经发出的添加请求。返回后请在“我的申请”核对结果。',
    stay: '留在此页', leave: '离开并稍后核对',
    fees: '学费', deadline: '截止日期', pending: '待核验', unspecified: '官网未说明',
    overview: '项目介绍', evidence: '信息核验', facts: '费用与申请时间', fit: '申请要求与我的情况',
    requirement: '学校要求', situation: '我的情况', judgement: 'Atlas 判断', advice: '建议',
    sources: '官网依据', openSource: '打开官网', sourceError: '暂时无法打开该网页，请稍后重试。',
    checked: '核验日期', show: '展开', hide: '收起', noFit: '暂未形成要求对照，请以官网公布的信息为准。',
    retrieved: '信息获取时间', fitScope: '这是基本申请资格对照，不代表录取概率。',
    noSources: '暂未记录可查看的官网依据。', noOverview: '项目介绍待补充。',
    next: '申请下一步', pendingStep: '暂时无法确认下一步，请稍后刷新。',
    checklistPending: '材料清单待确认', checklist: '材料清单', readiness: '材料准备情况',
    noApplications: '还没有申请项目', start: '去选校', applicationEmpty: '先从选校方案选择一个项目，Atlas 会为你建立申请档案。',
    applicationTitle: '申请详情', refreshApplication: '刷新申请',
    initializationDeferred: '申请档案已建立，部分材料清单或申请要求尚未准备好。当前不代表材料已经齐全。',
    materialsReadOnly: '你可以在下方查看材料要求；App 内上传材料尚未开放。',
    actionUnavailable: '这一步暂不能在 App 内办理。你可以查看下方要求，或返回申请列表。',
    actionReadOnly: '这一步暂不能在 App 内办理。',
    showRequirements: '查看材料与要求', noRequirements: '申请要求待确认，暂不能判断是否已满足。',
    requirements: '申请要求', applicationStatus: '当前阶段', progressUnknown: '进度待确认',
    account: '前往账户', sessionChanged: '请重新登录后继续。',
  },
  en: {
    title: 'My school plan', subtitle: 'Understand each programme before adding an application.',
    emptyTitle: 'No school plan yet', emptyBody: 'There are no programmes to choose from on this account. This version displays existing plans; completing your profile does not generate one automatically. Saved plans from the web preview will appear here.',
    freeBoundary: 'This version displays saved plans. It does not automatically generate or search for schools.',
    running: 'A school-planning task is still running. Existing results remain available; refresh later for updates.',
    failed: 'The latest school-planning task did not complete. Existing results remain available. Generation will not be retried automatically.',
    cancelled: 'The latest school-planning task was cancelled. Existing results remain available.',
    stale: 'Your study profile has changed. This plan has not been reassessed; compare it with your latest background before choosing.',
    profile: 'Complete study profile', reload: 'Refresh plan', back: 'Back to my applications', view: 'View programme',
    details: 'Programme details', add: 'Add to my applications', adding: 'Adding…', added: 'Added to my applications', viewApplication: 'View application',
    notSubmitted: 'This creates your application record. It does not submit an application to the school.',
    unavailable: 'This programme cannot currently be added. Return to your plan for the latest results.',
    missingSelection: 'This programme is no longer in the current plan. Return to the school plan to choose again.',
    backPlan: 'Back to school plan', uncertain: 'The result has not arrived. Your application may already exist. Check the result before continuing.',
    check: 'Check addition result', checking: 'Checking…', retryReady: 'This application was not found. You can add it again; only one record is kept for the same programme.',
    denied: 'Unable to add this programme. Refresh the plan to check it is still available.',
    leaveTitle: 'Addition is not confirmed', leaveBody: 'Leaving will not undo a request already sent. Check My applications when you return.',
    stay: 'Stay here', leave: 'Leave and check later',
    fees: 'Tuition', deadline: 'Deadline', pending: 'Pending verification', unspecified: 'Not specified officially',
    overview: 'Programme overview', evidence: 'Information verification', facts: 'Fees and application dates', fit: 'Requirements and my background',
    requirement: 'School requirement', situation: 'My background', judgement: 'Atlas assessment', advice: 'Advice',
    sources: 'Official sources', openSource: 'Open official website', sourceError: 'Unable to open this page. Please try again later.',
    checked: 'Checked on', show: 'Show', hide: 'Hide', noFit: 'A comparison is not available yet. Refer to the official requirements.',
    retrieved: 'Information retrieved on', fitScope: 'This compares basic eligibility. It is not an estimate of admission probability.',
    noSources: 'No official source is available to view yet.', noOverview: 'Programme overview is not available yet.',
    next: 'Application next step', pendingStep: 'The next step is not confirmed. Refresh later.',
    checklistPending: 'Materials checklist pending', checklist: 'Materials checklist', readiness: 'Materials readiness',
    noApplications: 'No applications yet', start: 'Choose a programme', applicationEmpty: 'Choose a programme from your school plan to create an application record.',
    applicationTitle: 'Application details', refreshApplication: 'Refresh application',
    initializationDeferred: 'Your application exists. Some materials checklists or requirements are not ready yet; this does not mean your materials are complete.',
    materialsReadOnly: 'You can review the requirements below. Uploading materials in the app is not available yet.',
    actionUnavailable: 'This step cannot be completed in the app yet. Review the requirements below or return to your applications.',
    actionReadOnly: 'This step cannot be completed in the app yet.',
    showRequirements: 'View materials and requirements', noRequirements: 'Requirements are pending. Readiness cannot be confirmed yet.',
    requirements: 'Application requirements', applicationStatus: 'Current stage', progressUnknown: 'Progress not confirmed',
    account: 'Go to Account', sessionChanged: 'Sign in again to continue.',
  },
} as const;
const labels = {
  verified: ['已核验', 'Verified'], partial: ['部分核验', 'Partially verified'], pending: ['待核验', 'Pending verification'],
  failed: ['核验未完成', 'Verification incomplete'], stale: ['信息待更新', 'Needs rechecking'], unavailable: ['暂无核验结果', 'Verification unavailable'],
  not_searched: ['待核验', 'Pending verification'], searching: ['核验进行中', 'Verification in progress'],
  source_not_found: ['暂未找到官网依据', 'Official source not found'], source_found: ['已有来源，待核验', 'Source found; verification pending'],
  extraction_failed: ['信息提取未完成', 'Extraction incomplete'], officially_unspecified: ['官网未说明', 'Not specified officially'],
  meets: ['符合', 'Meets'], likely_meets: ['可能符合', 'Likely meets'], needs_review: ['需要进一步确认', 'Needs review'],
  not_met: ['尚未满足', 'Not met'], not_required: ['无需提供', 'Not required'], unknown: ['待确认', 'Unconfirmed'],
  ready: ['已准备', 'Ready'], needs_update: ['需要更新', 'Needs updating'], missing: ['待准备', 'Missing'],
  uploaded: ['已上传', 'Uploaded'], reviewing: ['审核中', 'Under review'], accepted: ['已通过', 'Accepted'], rejected: ['需要修改', 'Needs revision'],
  satisfied: ['已满足', 'Satisfied'], likely_satisfied: ['可能满足', 'Likely satisfied'], action_required: ['需要处理', 'Action required'],
} as const;
export function schoolLabel(code: string, locale: ApiLocale): string {
  return (Object.hasOwn(labels, code) ? labels[code as keyof typeof labels]?.[locale === 'zh' ? 0 : 1] : undefined) ?? schoolCopy[locale].pending;
}
export function countryLabel(code: string, locale: ApiLocale): string {
  const countries: Record<string, readonly [string, string]> = { FR: ['法国', 'France'], GB: ['英国', 'United Kingdom'], US: ['美国', 'United States'], CA: ['加拿大', 'Canada'], AU: ['澳大利亚', 'Australia'], DE: ['德国', 'Germany'], NL: ['荷兰', 'Netherlands'], IE: ['爱尔兰', 'Ireland'], SG: ['新加坡', 'Singapore'], HK: ['中国香港', 'Hong Kong SAR'] };
  return Object.hasOwn(countries, code) ? countries[code]![locale === 'zh' ? 0 : 1] : code;
}
