import type { ProfileStringField } from '../../lib/api/profile-contract';
export const fieldLabels: Record<ProfileStringField, readonly [string, string]> = {
  educationLevel: ['当前或最高学历', 'Current or highest qualification'], currentInstitution: ['就读院校', 'Institution'],
  currentMajor: ['当前专业', 'Current major'], gpa: ['GPA / 平均分', 'GPA / average grade'],
  gradingScale: ['评分体系', 'Grading scale'], graduationYear: ['毕业或预计毕业年份', 'Graduation year'],
  experiences: ['实习、项目或其他经历（每行一项）', 'Experience (one item per line)'],
  targetDegree: ['目标学位', 'Target degree'], targetCountries: ['目标国家（可多选）', 'Target countries (multiple allowed)'],
  targetFields: ['目标专业方向（每行一项）', 'Target fields (one item per line)'], intakeYear: ['计划入学年份', 'Intake year'],
  intakeTerm: ['计划入学学期', 'Intake term'], annualBudgetMin: ['年度预算下限', 'Annual budget minimum'],
  annualBudgetMax: ['年度预算上限', 'Annual budget maximum'], budgetCurrency: ['预算币种', 'Budget currency'],
  cityPreferences: ['偏好城市（每行一项）', 'Preferred cities (one item per line)'], rankingPriority: ['排名与择校偏好', 'Ranking and school preferences'],
  careerGoal: ['职业目标', 'Career goal'],
};
export const options = {
  educationLevel: [['Bachelor', '本科', 'Bachelor'], ['Master', '硕士', 'Master'], ['Associate', '大专', 'Associate degree'], ['High School', '高中', 'High school']],
  gradingScale: [['100', '百分制', 'Out of 100'], ['4.0', '4.0 GPA', '4.0 GPA'], ['5.0', '5.0 GPA', '5.0 GPA'], ['10.0', '10.0 CGPA', '10.0 CGPA'], ['UK degree classification', '英国学位等级', 'UK classification'], ['Other', '其他', 'Other']],
  targetDegree: [['MSc', '硕士', "Master's degree"], ['Bachelor', '本科', "Bachelor's degree"], ['MBA', 'MBA', 'MBA'], ['PhD', '博士', 'PhD']],
  targetCountries: [['France', '法国', 'France'], ['United Kingdom', '英国', 'United Kingdom'], ['Australia', '澳大利亚', 'Australia']],
  budgetCurrency: [['EUR', '欧元 EUR', 'EUR'], ['GBP', '英镑 GBP', 'GBP'], ['USD', '美元 USD', 'USD'], ['CNY', '人民币 CNY', 'CNY']],
} as const;
export const profileCopy = {
  zh: {
    title: '我的留学档案', subtitle: '一次补充一部分，已经保存的信息会在后续步骤中复用。',
    steps: ['教育背景', '留学目标', '语言与预算', '核对资料'], next: '下一步', previous: '上一步',
    edit: '修改', review: '核对资料', saveDraft: '保存草稿', saving: '正在保存…', save: '保存并更新下一步',
    saved: '已保存到你的测试档案。首页的下一步会根据服务器最新结果更新。',
    unsaved: '有尚未保存的修改', unsavedBody: '离开会丢失本次未保存的内容。已保存的草稿仍会保留。',
    stay: '继续填写', discard: '放弃修改并离开', back: '返回', viewNext: '查看更新后的下一步', currentValue: '当前内容', leaveUnconfirmed: '离开此页（保存结果尚未确认）', savedFacts: '已保存资料的完整度',
    draftHint: '可以先留空不确定的信息，随时保存草稿。只有保存成功的内容才能在下次打开时恢复。',
    incomplete: '完整度由 Atlas 根据已保存资料计算，不是对你的评分。',
    language: '语言', qualification: '考试或资格', result: '成绩或等级', addLanguage: '添加语言', removeLanguage: '移除此语言',
    flexibleMajor: '可接受相邻专业或转专业方案', flexiblePathway: '可接受预科或桥梁方案',
    noValue: '尚未填写', yes: '可接受', no: '暂不接受', languageHeading: '语言与考试成绩',
    validation: '请检查以下项目后再保存：', validationGeneric: '资料未通过校验，请检查年份、预算和语言信息后再保存。',
    uncertain: '保存结果暂时无法确认，输入仍保留在此页。请先读取服务器上的最新档案，再决定是否重新保存。离开此页不会撤销服务器已经保存的内容。',
    checkSaved: '核对服务器上的档案', reloadFailed: '暂时无法读取服务器上的档案，请稍后再试。当前输入仍保留。',
    compare: '服务器当前保存的内容如下。核对后可使用该版本，或保留本页修改继续编辑。',
    useServer: '使用服务器版本', keepMine: '保留本页修改', pending: '材料中还有待确认的信息',
    pendingHint: '以下信息尚未自动写入档案。请核对后在对应字段填写；材料确认流程仍待开放。',
    saveUnsupported: '当前测试服务暂不支持保存此档案。输入仍保留，请联系测试负责人核对版本。', tooLarge: '填写内容过长，尚未保存。请缩短说明后再试。', rateLimited: '保存请求过于频繁，请稍等片刻再试。输入仍保留。', noPermission: '当前账号无权保存此档案。输入仍保留，请联系测试负责人核对权限。', refreshing: '正在读取最新保存状态…', sessionChanged: '登录状态已变化，请重新登录后再保存。',
  },
  en: {
    title: 'Study profile', subtitle: 'Complete one section at a time. Saved information is reused in later steps.',
    steps: ['Education', 'Study goals', 'Languages and budget', 'Review'], next: 'Next', previous: 'Back',
    edit: 'Edit', review: 'Review details', saveDraft: 'Save draft', saving: 'Saving…', save: 'Save and update next step',
    saved: 'Saved to your test profile. Your next step will refresh from the server.',
    unsaved: 'Unsaved changes', unsavedBody: 'Leaving discards these unsaved changes. Previously saved drafts remain available.',
    stay: 'Keep editing', discard: 'Discard and leave', back: 'Back', viewNext: 'View the updated next step', currentValue: 'Current value', leaveUnconfirmed: 'Leave with save outcome unconfirmed', savedFacts: 'Saved profile completeness',
    draftHint: 'You can leave uncertain details blank and save a draft. Only successfully saved information is restored next time.',
    incomplete: 'Atlas calculates completeness from your saved information. It is not a score of your abilities.',
    language: 'Language', qualification: 'Exam or qualification', result: 'Score or level', addLanguage: 'Add a language', removeLanguage: 'Remove language',
    flexibleMajor: 'Consider related subjects or a change of major', flexiblePathway: 'Consider foundation or pathway programmes',
    noValue: 'Not filled in', yes: 'Open to this', no: 'Not selected', languageHeading: 'Languages and results',
    validation: 'Check these fields before saving:', validationGeneric: 'Please check years, budget and language information before saving.',
    uncertain: 'The save outcome is not confirmed. Your edits remain here. Read the latest server profile before deciding whether to save again. Leaving does not undo anything already saved on the server.',
    checkSaved: 'Check the saved profile', reloadFailed: 'The saved profile could not be loaded. Try later; your edits remain here.',
    compare: 'This is the version currently saved on the server. You can use it or keep editing your local changes.',
    useServer: 'Use server version', keepMine: 'Keep my changes', pending: 'Information awaiting confirmation',
    pendingHint: 'These extracted details have not been added to your profile automatically. Check them before filling the matching fields. Document confirmation is not available yet.',
    saveUnsupported: 'The current test service does not accept this profile save. Your edits remain here; ask the team to check the version.', tooLarge: 'This profile is too long to save. Shorten the descriptions and try again.', rateLimited: 'Too many save requests. Wait a little before retrying; your edits remain here.', noPermission: 'This account cannot save the profile. Your edits remain here; ask the team to check permissions.', refreshing: 'Reading the latest saved state…', sessionChanged: 'Your sign-in state changed. Sign in again before saving.',
  },
} as const;
